### PR TITLE
Removed (most) unnecessary CSS

### PR DESCRIPTION
**Pull request by XYQuadrat**
Custom Bootstrap build is included in config.json

### CODE REVIEW

**Comment by XYQuadrat** [comment]
By now, this is only done for kontalk.net. Kontalk.org coming soon

**Comment by daniele-athome** [comment]
Thanks, nice work!
Please note that I still have not merged this PR because I'm waiting for kontalk.org too :-)

**Comment by XYQuadrat** [comment]
Kontalk.org seems not to have bootstrap included, and so there is nothing to change except manually removing selectors (which might be bad for future enhancements).

**Comment by daniele-athome** [comment]
Website is now live, thank you!

**Pull request merged**
