### PR TITLE
added Link to help pages 

### PR DESCRIPTION
**Pull request by webratte**
As the title says ;-)

### CODE REVIEW

**Comment by daniele-athome** [comment]
Thanks @webratte, but I don't really like it there... the fact is this website doesn't allow for extra information very well...  any other ideas?

**Comment by webratte** [comment]
Users should find informations as fast as possible.
The more they find on there own, the less they will ask you I hope.
Playstore? Change the sentense "E-mail us at devteam@kontalk.org if you have any issues!!" into "E-mail us at devteam@kontalk.org or check our help pages https://github.com/kontalk/androidclient/wiki/FAQ if you have any issues!!

But there is already a link to permissions.
Too much links are not good I think.

I will think about it and talk about it with friends.

**Comment by webratte** [comment]
I have just talked with a friend. I asked him what he would do if he had a problem with a program.
His fast answere was "I search the official website inside the program and hope I will find any informations. The second try would be to ask a friend or google..."

Take a look to my mail providers website: https://mailbox.org/
They have all important (and less important) infos in the footer..
From time to time I take a look if there interesting news.

What I want to say:
The official website should work to give informations to users.
Currently yor website is a (of course beautifull) Advertisement poster ;-)
Wy not put helpfull informations on it?

**Comment by daniele-athome** [comment]
You're right, but the footer needs to be redesigned to be more like the one of mailbox.org (I see a lot of websites design the footer like that). I'll look into it.

**Pull request merged**
